name: Deploy CLI

on:
    push:
      branches:
        - 'main'
      paths: ['apps/cli/**','.github/workflows/deploy-cli.yml']

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: alpha
    name: Build and push Web docker image for release
    if: github.ref == 'refs/heads/main'
  
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
            version: 9.7.1
  
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:cli
  
      - name: Publish to NPM
        run: pnpm run publish:cli
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}