name: Deploy CLI

on:
    push:
      branches:
        - 'main'
      paths: ['apps/cli/**','.github/workflows/deploy-cli.yml']

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: alpha
    name: Build and push Web docker image for release
    if: github.event.ref == 'refs/heads/main'
  
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.2.0
          run_install: false
          
      - name: Get pnpm store directory
        shell: bash
        run: |
            echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
  
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
              ${{ runner.os }}-pnpm-store-
  
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:cli
  
      - name: Publish to NPM
        run: pnpm run publish:cli
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}